"""
Integration tests against Sample/unit_tester.csv.

unit_tester.csv is generated by running Sample/unit_tester.ps1 inside a
Procmon-monitored Windows VM via Noriben:

    python.exe Noriben.py -t 30 --cmd "powershell.exe -ExecutionPolicy Bypass -NonInteractive -NoProfile -File C:\\path\\to\\unit_tester.ps1"

Commit the resulting unit_tester.csv to Sample/ and these tests will run on
every subsequent test invocation.  When a new parse_csv() feature is added,
update unit_tester.ps1, regenerate unit_tester.csv, and add assertions below.

All tests are skipped automatically when unit_tester.csv is absent.
"""

import os
import unittest

import Noriben

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
_TESTS_DIR       = os.path.dirname(__file__)
_REPO_ROOT       = os.path.dirname(_TESTS_DIR)
_UNIT_TESTER_CSV = os.path.join(_REPO_ROOT, 'Sample', 'unit_tester.csv')
_CONFIG_PATH     = os.path.join(_REPO_ROOT, 'Noriben.config')


def _load_config():
    """Load the real Noriben.config approvelists when available."""
    if os.path.exists(_CONFIG_PATH):
        Noriben.read_config(_CONFIG_PATH)
    else:
        # Fallback: empty approvelists so nothing is filtered
        Noriben.config = {
            'yara_folder': '', 'generalize_paths': False,
            'virustotal_api_key': '', 'disable_file_hash': True,
            'disable-file-hash': True, 'debug': False,
            'output_folder': '', 'hash_type': 'SHA256', 'txt_extension': 'txt',
        }
        Noriben.global_approvelist = []
        Noriben.cmd_approvelist    = []
        Noriben.file_approvelist   = []
        Noriben.reg_approvelist    = []
        Noriben.net_approvelist    = []
        Noriben.hash_approvelist   = []

    Noriben.exe_cmdline       = ''
    Noriben.time_exec         = 0.0
    Noriben.time_process      = 0.0
    Noriben.path_general_list = []
    Noriben.has_yara          = False


# ---------------------------------------------------------------------------
# Helper — run parse_csv once and cache the result for the whole module
# ---------------------------------------------------------------------------
_cached = None

def _parse():
    global _cached
    if _cached is None:
        _load_config()
        report, timeline = [], []
        json_data = Noriben.parse_csv(_UNIT_TESTER_CSV, report, timeline, process_tree=True)
        _cached = (report, timeline, json_data)
    return _cached


@unittest.skipUnless(os.path.exists(_UNIT_TESTER_CSV),
                     'unit_tester.csv not present — run Sample/unit_tester.ps1 in a VM first')
class UnitTesterProcessTests(unittest.TestCase):
    """Process Create events and exit code annotations."""

    def _creates(self):
        report, _, _ = _parse()
        return [l for l in report if l.startswith('[CreateProcess]')]

    def test_at_least_two_process_creates(self):
        # unit_tester.ps1 spawns cmd.exe twice (exit 0 and exit 1)
        self.assertGreaterEqual(len(self._creates()), 2)

    def test_cmd_exe_appears_in_creates(self):
        self.assertTrue(any('cmd.exe' in l for l in self._creates()))

    def test_nonzero_exit_annotated(self):
        # cmd.exe /c exit 1  →  [Exit: 0x00000001 - Generic Error]
        annotated = [l for l in self._creates() if '[Exit:' in l]
        self.assertGreaterEqual(len(annotated), 1)

    def test_exit_code_one_annotation_present(self):
        creates = self._creates()
        self.assertTrue(any('0x00000001' in l for l in creates),
                        'Expected [Exit: 0x00000001] annotation not found in:\n' +
                        '\n'.join(creates))

    def test_zero_exit_produces_no_annotation(self):
        # At least one cmd.exe spawn (exit 0) must have no [Exit:] tag
        creates = self._creates()
        unannotated = [l for l in creates if 'cmd.exe' in l and '[Exit:' not in l]
        self.assertGreaterEqual(len(unannotated), 1)

    def test_json_processes_populated(self):
        _, _, json_data = _parse()
        self.assertGreaterEqual(len(json_data['processes']), 2)

    def test_json_exit_code_field_present_for_nonzero(self):
        _, _, json_data = _parse()
        codes = [p['exit_code'] for p in json_data['processes'] if 'exit_code' in p]
        self.assertIn('0x00000001', codes)

    def test_process_tree_section_in_report(self):
        report, _, _ = _parse()
        self.assertTrue(any('Process Tree:' in l for l in report))


@unittest.skipUnless(os.path.exists(_UNIT_TESTER_CSV),
                     'unit_tester.csv not present — run Sample/unit_tester.ps1 in a VM first')
class UnitTesterFileTests(unittest.TestCase):
    """File Create, Rename, and Delete events."""

    def _file_lines(self):
        report, _, _ = _parse()
        return [l for l in report if l.startswith('[CreateFile]') or
                                     l.startswith('[RenameFile]') or
                                     l.startswith('[DeleteFile]')]

    def test_file_events_present(self):
        self.assertGreater(len(self._file_lines()), 0)

    def test_noriben_test_dir_in_file_events(self):
        self.assertTrue(any('NoribenTest' in l for l in self._file_lines()))

    def test_file_create_event_present(self):
        creates = [l for l in self._file_lines() if l.startswith('[CreateFile]')]
        self.assertGreater(len(creates), 0)

    def test_file_delete_event_present(self):
        deletes = [l for l in self._file_lines() if l.startswith('[DeleteFile]')]
        self.assertGreater(len(deletes), 0)

    def test_json_files_populated(self):
        _, _, json_data = _parse()
        self.assertGreater(len(json_data['files']), 0)


@unittest.skipUnless(os.path.exists(_UNIT_TESTER_CSV),
                     'unit_tester.csv not present — run Sample/unit_tester.ps1 in a VM first')
class UnitTesterRegistryTests(unittest.TestCase):
    """Registry Create, Set Value, Delete Value, and Delete Key events."""

    def _reg_lines(self):
        report, _, _ = _parse()
        return [l for l in report if l.startswith('[RegCreateKey]') or
                                     l.startswith('[RegSetValue]')  or
                                     l.startswith('[RegDeleteValue]') or
                                     l.startswith('[RegDeleteKey]')]

    def test_registry_events_present(self):
        self.assertGreater(len(self._reg_lines()), 0)

    def test_noriben_test_key_in_registry_events(self):
        self.assertTrue(any('NoribenTest' in l for l in self._reg_lines()),
                        'NoribenTest registry key not found in:\n' +
                        '\n'.join(self._reg_lines()))

    def test_reg_set_value_present(self):
        sets = [l for l in self._reg_lines() if l.startswith('[RegSetValue]')]
        self.assertGreater(len(sets), 0)

    def test_json_registry_populated(self):
        _, _, json_data = _parse()
        self.assertGreater(len(json_data['registry']), 0)


@unittest.skipUnless(os.path.exists(_UNIT_TESTER_CSV),
                     'unit_tester.csv not present — run Sample/unit_tester.ps1 in a VM first')
class UnitTesterNetworkTests(unittest.TestCase):
    """UDP DNS traffic, TCP connection (example.com), and Unique Hosts.

    unit_tester.ps1 calls GetHostAddresses("example.com") which generates UDP
    DNS traffic via svchost, and TcpClient.Connect("93.184.216.34", 80) which
    Procmon logs as TCP Connect/Reconnect/Send/Receive events from powershell.exe.
    """

    def _net_lines(self):
        report, _, _ = _parse()
        return [l for l in report if l.startswith('[TCP]') or
                                     l.startswith('[UDP]') or
                                     l.startswith('[DNS Query]')]

    def test_network_events_present(self):
        self.assertGreater(len(self._net_lines()), 0)

    def test_udp_events_captured(self):
        # VM generates UDP DNS/mDNS/NetBIOS traffic
        udp = [l for l in self._net_lines() if l.startswith('[UDP]')]
        self.assertGreater(len(udp), 0,
                           'Expected [UDP] events in report, got:\n' +
                           '\n'.join(self._net_lines()))

    def test_dns_udp_traffic_captured(self):
        # GetHostAddresses("example.com") sends UDP to :53
        udp = [l for l in self._net_lines() if l.startswith('[UDP]')]
        self.assertTrue(any(':53' in l for l in udp),
                        'Expected UDP :53 traffic, got:\n' + '\n'.join(udp))

    def test_tcp_connection_to_example_com(self):
        # TcpClient.Connect("93.184.216.34", 80) — logged as TCP Connect/Reconnect
        tcp = [l for l in self._net_lines() if l.startswith('[TCP]')]
        self.assertTrue(any('93.184.216.34' in l for l in tcp),
                        'TCP event to 93.184.216.34 not found in:\n' + '\n'.join(tcp))

    def test_unique_hosts_populated(self):
        _, _, json_data = _parse()
        self.assertGreater(len(json_data['unique_hosts']), 0)

    def test_example_com_ip_in_unique_hosts(self):
        _, _, json_data = _parse()
        self.assertIn('93.184.216.34', json_data['unique_hosts'])

    def test_unique_hosts_excludes_localhost(self):
        _, _, json_data = _parse()
        self.assertNotIn('localhost', json_data['unique_hosts'])
        self.assertNotIn('127.0.0.1', json_data['unique_hosts'])

    def test_json_network_populated(self):
        _, _, json_data = _parse()
        self.assertGreater(len(json_data['network']), 0)


@unittest.skipUnless(os.path.exists(_UNIT_TESTER_CSV),
                     'unit_tester.csv not present — run Sample/unit_tester.ps1 in a VM first')
class UnitTesterModuleLoadTests(unittest.TestCase):
    """Load Image events from unusual (non-system) paths.

    Block 12 of unit_tester.ps1 compiles NoribenTest.dll into %TEMP%\\NoribenTest\\
    and loads it via reflection, producing a Load Image event outside the standard
    dll_approvelist paths.  These tests require a CSV generated from the v1.2+
    unit_tester.ps1; the section-header and json-key tests pass against any CSV.
    """

    def _module_lines(self):
        report, _, _ = _parse()
        return [l for l in report if l.startswith('[LoadImage]')]

    def test_module_loads_section_present(self):
        report, _, _ = _parse()
        self.assertTrue(any('Module Loads:' in l for l in report))

    def test_json_modules_key_present(self):
        _, _, json_data = _parse()
        self.assertIn('modules', json_data)

    def test_noribentest_dll_load_captured(self):
        # Requires CSV from unit_tester.ps1 v1.2+ (block 12)
        self.assertTrue(
            any('NoribenTest.dll' in l for l in self._module_lines()),
            'NoribenTest.dll [LoadImage] not found — re-run unit_tester.ps1 in VM:\n'
            + '\n'.join(self._module_lines() or ['(no [LoadImage] events)'])
        )

    def test_noribentest_dll_in_json_modules(self):
        _, _, json_data = _parse()
        paths = [m['path'] for m in json_data['modules']]
        self.assertTrue(any('NoribenTest.dll' in p for p in paths),
                        'NoribenTest.dll not found in json modules:\n' + '\n'.join(paths))

    def test_system32_dlls_not_in_module_loads(self):
        # dll_approvelist should suppress standard system DLLs
        self.assertFalse(
            any(r'\System32\\' in l or '/System32/' in l for l in self._module_lines()),
            'System32 DLL leaked through dll_approvelist:\n' +
            '\n'.join(l for l in self._module_lines() if 'System32' in l)
        )


@unittest.skipUnless(os.path.exists(_UNIT_TESTER_CSV),
                     'unit_tester.csv not present — run Sample/unit_tester.ps1 in a VM first')
class UnitTesterReportStructureTests(unittest.TestCase):
    """Overall report completeness."""

    def test_all_section_headers_present(self):
        report, _, _ = _parse()
        text = '\n'.join(report)
        for section in ('Processes Created:', 'Module Loads:', 'File Activity:',
                        'Registry Activity:', 'Network Traffic:', 'Unique Hosts:'):
            self.assertIn(section, text)

    def test_json_metadata_version_matches(self):
        _, _, json_data = _parse()
        self.assertEqual(json_data['metadata']['noriben_version'], Noriben.__VERSION__)

    def test_timeline_has_entries(self):
        _, timeline, _ = _parse()
        self.assertGreater(len(timeline), 0)

    def test_timeline_has_process_entry(self):
        _, timeline, _ = _parse()
        self.assertTrue(any('CreateProcess' in str(row) for row in timeline))

    def test_timeline_has_network_entry(self):
        _, timeline, _ = _parse()
        self.assertTrue(any('TCP' in str(row) or 'UDP' in str(row) for row in timeline))


if __name__ == '__main__':
    unittest.main()
